version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-management-system
    container_name: task-management-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - task-management

  nginx:
    image: nginx:alpine
    container_name: task-management-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - task-management

  db:
    image: mysql:8.0
    container_name: task-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: task_user
      MYSQL_PASSWORD: task_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - task-management

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task-management-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - task-management

volumes:
  db_data:
    driver: local

networks:
  task-management:
    driver: bridge
